### PR TITLE
Minor fix for unnecessary operations.

### PR DESCRIPTION
**Pull request by corona10**
For this weekend, I am going to read your repos.
Actually, this PR is not significant.
Just one thing I noticed, while I read your code. 
There was an unnecessary operations which is to find the smallest pid.

If `ts` does not exist, it doesn't have to compare old one.

### CODE REVIEW

**Comment by pombredanne** [comment]
@corona10 Thanks!

**Comment by pombredanne** [comment]
were you able to run the tests locally alright btw?

**Comment by corona10** [comment]
@pombredanne Sure! Everything worked fine. It will be great if there are some install guide for `altgraph`,`docopt` by installed `pip`.

**Comment by pombredanne** [comment]
@corona10 the only thing needed normally is to checkout a clone and run `./configure` then `. bin/activate`
This will install all the deps in a virtualenv including the test deps. And fetches them all locally from the `thirdparty` directory ensuring reproducible envs.

**Comment by pombredanne** [comment]
I will merge this is in as soon as a the CI tests pass.

**Comment by corona10** [comment]
@pombredanne  That's nice tips. Thanks!

**Comment by pombredanne** [comment]
Merged/ Thanks!

**Comment by pombredanne** [comment]
Comment for future commits messages:
1. we like to prefix the 1st line with an issue number. Here this was a trivial change so it did not warrant it. If it had one a you would have added `#156` as a prefix to the first line.

2. we like to tell what the commit is about and use an imperative style, like if you were giving an order to the codebase with your commit:

e.g rather than : `Minor fix for unnecessary operations.`
may be `#123 Remove unnecessary operations.`
or 
```
#123 Remove unnecessary operations.

   * If the ts timestamp does not exist, do not compare 
     with old one.
```

3. You need to add a signoff to your commit. So the final message would have looked like this:


```
#123 Remove unnecessary operations.

   * If the ts timestamp does not exist, do not compare 
     with old one.

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
```

**Comment by pombredanne** [comment]
I summarized our guidelines here: https://github.com/nexB/aboutcode/wiki/Writing-good-commit-messages

**Comment by corona10** [comment]
@pombredanne Sounds great. Thank you for complete documentations. I will take a look at it and follow.

**Pull request merged**
